import { registerViewInit } from './ui.js';
import { registerViewRefresh, t } from './i18n.js';
import { loadModule, saveModule, registerAppKey, uid } from './store.js';
import { countdownInfo } from './boun-gpa-utils.js';
import { escapeHtml } from './grades.js';
const NS='planner'; registerAppKey(NS); let data=loadModule(NS); data.items=Array.isArray(data.items)?data.items:[];
const TYPES={Exam:'planner.typeExam',Assignment:'planner.typeAssignment',Quiz:'planner.typeQuiz',Project:'planner.typeProject'};
const typeLabel=x=>t(TYPES[x]||'planner.typeAssignment');
const persist=()=>saveModule(NS,data);
function countdown(iso){const c=countdownInfo(iso,new Date());if(c.invalid)return t('planner.due');if(c.overdue)return t('planner.overdue');if(c.ms<86400000)return t('planner.hoursLeft',{n:Math.max(1,Math.ceil(c.ms/3600000))});if(c.daysLeft===1)return t('planner.dueTomorrow');return t('planner.daysLeft',{n:c.daysLeft});}
function render(){const root=document.getElementById('plannerView');if(!root)return; data=loadModule(NS); data.items=Array.isArray(data.items)?data.items:[]; const items=[...data.items].sort((a,b)=>new Date(a.due)-new Date(b.due));
 root.innerHTML=`<section class="module-shell"><div class="module-heading"><div><p class="eyebrow">BOUN GPA CALCULATOR</p><h2>${t('planner.title')}</h2><p>${t('planner.desc')}</p></div><div class="module-actions"><button class="btn btn-secondary" data-action="ics">${t('planner.exportIcs')}</button><button class="btn btn-primary" data-action="add">${t('planner.add')}</button></div></div><div class="planner-list">${items.map(i=>`<article class="planner-item urgency-${countdownInfo(i.due,new Date()).tier} ${i.done?'is-done':''}"><div><span class="planner-type">${escapeHtml(typeLabel(i.type))}</span><h3>${escapeHtml(i.title)}</h3><p>${escapeHtml(i.course||'')}</p></div><div class="planner-due"><strong>${new Date(i.due).toLocaleDateString(undefined,{dateStyle:'medium'})}</strong><span>${countdown(i.due)}</span></div><div class="planner-actions"><button class="btn btn-ghost" data-action="done" data-id="${escapeHtml(i.id)}" aria-label="${escapeHtml(i.done?t('planner.markUndone'):t('planner.markDone'))}">${i.done?t('planner.markUndone'):t('planner.markDone')}</button><button class="btn btn-ghost" data-action="edit" data-id="${escapeHtml(i.id)}" aria-label="${escapeHtml(t('common.edit'))}">${t('common.edit')}</button><button class="btn btn-ghost danger" data-action="delete" data-id="${escapeHtml(i.id)}" aria-label="${escapeHtml(t('common.delete'))}">${t('common.delete')}</button></div></article>`).join('')}</div>${!items.length?`<div class="empty-state"><h3>${t('planner.empty')}</h3><p>${t('planner.emptyDesc')}</p></div>`:''}</section>`;
 root.querySelector('[data-action="add"]')?.addEventListener('click',()=>edit()); root.querySelectorAll('[data-action="edit"]').forEach(b=>b.onclick=()=>edit(b.dataset.id)); root.querySelectorAll('[data-action="delete"]').forEach(b=>b.onclick=()=>{data.items=data.items.filter(i=>i.id!==b.dataset.id);persist();render();}); root.querySelectorAll('[data-action="done"]').forEach(b=>b.onclick=()=>{const i=data.items.find(i=>i.id===b.dataset.id);if(i){i.done=!i.done;persist();render();}}); root.querySelector('[data-action="ics"]')?.addEventListener('click',exportICS);
}
function edit(id){const old=data.items.find(i=>i.id===id)||{id:uid(),type:'Assignment',done:false};const title=prompt(t('planner.titleField'),old.title||'');if(title===null||!title.trim())return;const course=prompt(t('planner.course'),old.course||'')||'';const due=prompt(t('planner.due')+' (YYYY-MM-DDTHH:MM)',old.due||new Date(Date.now()+86400000).toISOString().slice(0,16));if(!due||!Number.isFinite(new Date(due).getTime()))return;const rawType=prompt(t('planner.type'),typeLabel(old.type));const type=Object.keys(TYPES).includes(rawType)?rawType:(old.type||'Assignment');const item={...old,title:title.trim(),course,due,type};const n=data.items.findIndex(i=>i.id===id);if(n<0)data.items.push(item);else data.items[n]=item;persist();render();}
function icsText(value){return String(value??'').replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\r\n|\r|\n/g,'\\n');}
function exportICS(){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//BOUN GPA Calculator//Planner//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH'];data.items.filter(i=>!i.done&&Number.isFinite(new Date(i.due).getTime())).forEach(i=>{lines.push('BEGIN:VEVENT',`UID:${icsText(i.id)}@boun-gpa-calculator`,`DTSTAMP:${icsDate(new Date())}`,`DTSTART:${icsDate(new Date(i.due))}`,`SUMMARY:${icsText(i.title)}`,'END:VEVENT');});lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='boun-gpa-planner.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function icsDate(date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');}
registerViewInit('planner',()=>render());registerViewRefresh('planner',render);
